### ISSUE TITLE
Writing 50mb output file for 10mb input file after shrink operation

### ISSUE THREAD

**Issue by jonathan-kosgei** [jcupitt/node-vips#3]
Hi!
libvips has every possible thing I could possibly need for a very involving project and is super fast!
I'm trying to use it from node because there're a few things sharp doesn't do that libvips supports.

The following script produced an image that was 5 times the input size i.e. ~10.2mb to ~56.8mb

```
var vips = require('vips-ffi');
var image = vips.Image.newFromFile('patrick-hendry-547014-unsplash.jpg');
image.shrink(50, 50)
image.writeToFile('testc.png')
```

How would I resize an image?

**Comment by jcupitt** [comment]
Hello @jonathan-kosgei,

Your example should work, though shouldn't it be `require('vips')`? I think `vips-ffi` might be a different project. 

I see:

```javascript
#!/usr/bin/env node
  
'use strict';

var vips = require('vips');

var image = vips.Image.newFromFile(process.argv[2]);
image = image.shrink(50, 50);
image.writeToFile(process.argv[3]);
```

Then:

```
$ vipsheader ~/pics/wtc.jpg
/home/john/pics/wtc.jpg: 9372x9372 uchar, 3 bands, srgb, jpegload
$ time ./shrink.js ~/pics/wtc.jpg x.png
real	0m2.500s
user	0m2.994s
sys	0m0.619s
$ vipsheader x.png 
x.png: 187x187 uchar, 3 bands, srgb, pngload
```

That's rather a slow way to shrink an image though. You'll find `thumbnail` is a lot quicker:

```javascript
var image = vips.Image.thumbnail(process.argv[2], 187);
image.writeToFile(process.argv[3]);
```

Gives:

```
$ time ./shrink.js ~/pics/wtc.jpg x.png
real	0m0.807s
user	0m0.807s
sys	0m0.025s
```

There are some examples here:

https://github.com/jcupitt/node-vips/tree/master/example

**Comment by jcupitt** [comment]
Oh duh, you're right, it is `vips-ffi`.

**Comment by jonathan-kosgei** [comment]
Thanks! That worked well and was much faster. Is there a function that takes the height as well?

**Comment by jcupitt** [comment]
Sure, `thumbnail` has loads of options:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

**Comment by jonathan-kosgei** [comment]
Thanks!
